-- Create wallet table for user balances
CREATE TABLE IF NOT EXISTS easyride_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

-- Create enum for recharge request status
DO $$ BEGIN
    CREATE TYPE recharge_status_enum AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create recharge requests table
CREATE TABLE IF NOT EXISTS easyride_recharge_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('Bkash', 'Nagad', 'Rocket')),
    phone_number VARCHAR(20) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL UNIQUE,
    status recharge_status_enum DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    processed_by UUID REFERENCES profiles(id),
    rejection_reason TEXT,
    CONSTRAINT valid_status_transition CHECK (
        (status = 'pending' AND processed_at IS NULL AND processed_by IS NULL) OR
        (status IN ('approved', 'rejected') AND processed_at IS NOT NULL AND processed_by IS NOT NULL)
    )
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_recharge_requests_user_id ON easyride_recharge_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_recharge_requests_status ON easyride_recharge_requests(status);
CREATE INDEX IF NOT EXISTS idx_recharge_requests_created_at ON easyride_recharge_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallets_user_id ON easyride_wallets(user_id);

-- Create trigger to update wallet updated_at timestamp
CREATE OR REPLACE FUNCTION update_wallet_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER wallet_updated_at_trigger
    BEFORE UPDATE ON easyride_wallets
    FOR EACH ROW
    EXECUTE FUNCTION update_wallet_timestamp();

-- Insert initial wallet for existing users (if any)
INSERT INTO easyride_wallets (user_id, balance)
SELECT id, 0.00
FROM profiles
WHERE id NOT IN (SELECT user_id FROM easyride_wallets)
ON CONFLICT (user_id) DO NOTHING;
