import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * Root Layout Component
 * Defines the global layout structure for the application.
 * Applies global fonts and styles.
 * 
 * @component
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - The child components to render within the layout
 * @returns {JSX.Element} The rendered root layout
 */
export default function RootLayout({
    children,
}) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
                <Toaster />
            </body>
        </html>
    );
}
